# Generated by Django 5.1.5 on 2025-02-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredcourse',
            name='course_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='desiredcourse',
            name='student_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='desiredcourse',
            unique_together={('student_id', 'course_code')},
        ),
    ]
