# Generated by Django 5.1.5 on 2025-03-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_desiredcourse_course_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('course_code', models.TextField()),
                ('course_details', models.JSONField()),
            ],
            options={
                'unique_together': {('student_id', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='SavedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('schedule_name', models.CharField(max_length=100)),
                ('is_saved', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(related_name='schedules', to='courses.savedcourse')),
            ],
            options={
                'unique_together': {('student_id', 'schedule_name')},
            },
        ),
    ]
