# Generated by Django 5.1.5 on 2025-02-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session", "0002_remove_student_agreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
