# Generated by Django 5.1.5 on 2025-02-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
